{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "todo.fullname" . }}-fe
spec:
  {{- with .Values.route.host }}
  host: {{ . }}
  {{- end }}
  {{- with .Values.fe.route_path }}
  path: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "todo.fullname" . }}-fe
  port:
    targetPort: {{ .Values.fe.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
