apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-fe
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fe.service.type }}
  ports:
    - port: {{ .Values.fe.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo.selectorLabels" . | nindent 4 }}
