services:
  mysql-data:
    image: docker.io/library/mysql:8.0
    container_name: lab3-database
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: lab3-db
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password

volumes:
  mysql-data:
