services:
  mysql-data:
    image: docker.io/library/mysql:8.0
    container_name: lab3-database
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 5

volumes:
  mysql-data:
