services:
  spring-lab3-app-json:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql-data:
        condition: service_healthy
#    env_file:
#      - .env-json
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/application.properties  # Location of application properties.
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  spring-lab3-app-non-json:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mysql-data:
        condition: service_healthy
#    env_file:
#      - .env-non-json
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/application.properties  # Location of application properties.
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  mysql-data:
    image: docker.io/library/mysql:8.0
    container_name: lab3-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: labpassword
      MYSQL_DATABASE: lab3
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
