services:
  spring-lab3-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-data
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/${MYSQL_DATABASE}  # Database URL.
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}  # Database username.
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}  # Database password.
      - SPRING_CONFIG_LOCATION=file:/app/application.properties  # Location of application properties.
    networks:
      - spring-lab3-network
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  mysql-data:
    image: docker.io/library/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: labpassword
      MYSQL_DATABASE: lab3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-lab3-network

volumes:
  mysql-data:

networks:
  spring-lab3-network:
    driver: bridge